# Preston Jackson's personal website Apache configuration file

# Enable the following modules in /etc/apache2/httpd.conf on macOS or via
# a2enmod on Debian
# - mod_alias (for ScriptAlias)
# - mod_cgi or mod_cgid (for CGI scripts)
# - mod_env (to set the Path for cmark-gfm)
# - mod_include (enable server-side includes)
# - mod_rewrite (for URL rewriting for the blog, research journal, and API)
# - mod_ssl (for HTTPS, if needed)

# Define the site root directory and include this configuration
# On macOS, set this in /etc/apache2/httpd.conf
# <VirtualHost *:80>
#   Define SITE_ROOT /Library/Webserver
#   Include /Library/WebServer/prestonjackson.com/site/conf/apache2/prestonjackson.com.conf
# </VirtualHost>

# Or on Debian, set this in /etc/apache2/sites-available/prestonjackson.com.conf
# <VirtualHost *:80>
#   Define SITE_ROOT /var/www
#   Include /var/www/prestonjackson.com/site/conf/apache2/prestonjackson.com.conf
# </VirtualHost>
#
# And this in /etc/apache2/sites-available/prestonjackson.com-le-ssl.conf
# <VirtualHost *:443>
#   Define SITE_ROOT /var/www
#   Include /var/www/prestonjackson.com/site/conf/apache2/prestonjackson.com.conf
#</VirtualHost>

# Contact info
ServerAdmin web@prestonjackson.com


# Server name and aliases
ServerName prestonjackson.com
ServerAlias www.prestonjackson.com
ServerAlias api.prestonjackson.com
ServerAlias localhost  # For local development
# ServerName localhost:80


# Log locations
<IfDefine !APACHE_LOG_DIR>
    Define APACHE_LOG_DIR /var/log/apache2
</IfDefine>
ErrorLog ${APACHE_LOG_DIR}/prestonjackson.com.error.log
CustomLog ${APACHE_LOG_DIR}/prestonjackson.com.access.log combined


# Document root
DocumentRoot "${SITE_ROOT}/prestonjackson.com/site/doc"


# Server side includes (which need access to cmark for processing markdown)
<Directory "${SITE_ROOT}/prestonjackson.com/site/doc">
    # Ignore .htaccess files in this directory
    AllowOverride None

    # Grant access to the html files in the doc root
    Require all granted

    # Turn on server-side includes (SSI) here ("+" means to add this option
    # to the existing list of options)
    Options +Includes
    
    # Use the executable bit to indicate html files that will be processed
    # by the SSI engine. "full" sends the Last-Modified header, which is
    # useful for caching
    XBitHack full

    # Include the cmark-gfm bin path
    SetEnv PATH "/usr/local/bin:${PATH}"
</Directory>


# Set up rewrites for posts and articles to be injected into templates
<IfModule rewrite_module>
    RewriteEngine On

    # Rewrite the entry name to a URL param
    # Capture the filename (ending in .md), then add it as the post param
    # [PT] = Passthrough (reprocess generated URL)
    # [QSA] = Query String Append (from request to rewritten request)
    RewriteRule ^/blog/(.+.md)$ /blog/blog.html?$1 [PT,QSA]

    # Rewrite entries for the research journal
    RewriteRule ^/research/(.+.md)$ /research/research.html?$1 [PT,QSA]

    # Rewrite API calls to the gateway script
    RewriteRule ^/api/(.*)$ /api/gateway.py?$1 [PT,QSA]
</IfModule>


# Turn on common gateway interface (CGI) scripting
<IfModule alias_module>
    # Map the /api/ URL to the CGI directory
    ScriptAlias "/api/" "${SITE_ROOT}/prestonjackson.com/site/api/"
</IfModule>        
<Directory "${SITE_ROOT}/prestonjackson.com/site/api/">
    # Ignore .htaccess files in this directory
    AllowOverride None  

    # Grant access to the CGI directory
    Require all granted
    
    # Only allow .cgi scripts (or non-suffix files with executable bit set
    # seem to work)
    Options +ExecCGI
    AddHandler cgi-script .cgi
</Directory>


# Allow writing documents with UTF-8 encoding for simplified handling of
# special characters
AddDefaultCharset UTF-8
