#!/usr/bin/env python3

import io
import logging
import os
import sys

import gateway

log = logging.getLogger(__name__)

ALLOWED_ORIGINS = "null"
ALLOWED_HEADERS = "Content-Type"
ALLOWED_METHODS = "OPTIONS, GET, POST"

def handleOptions(headers, body, response):
    print("Status: 204 No Content", file=response)
    print(f"Access-Control-Allow-Origin: {ALLOWED_ORIGINS}", file=response)
    print(f"Access-Control-Allow-Headers: {ALLOWED_HEADERS}", file=response)
    print(f"Access-Control-Allow-Methods: {ALLOWED_METHODS}", file=response)


def handlePost(headers, body, response):
    print("Status: 200 OK", file=response)
    print("Access-Control-Allow-Origin: null", file=response)
    print("Content-Type: text/html\n", file=response)

    print("<html><body><pre><code>", file=response)
    print(body, file=response)
    print("</code></pre></body></html>", file=response)


def handleGet(headers, body, response):
    print("Status: 200 OK", file=response)


def logRequest(method, uri, protocol, headers, body, env):
    log.info(f"{method} {uri} {protocol}")
    log.info("-----HEADERS-----")
    for key, value in headers.items():
        log.info(f"{key}: {value}")

    log.info("-----ENV------")
    for key, value in env.items():
        log.info(f"{key}: {value}")

    log.info("-----BODY-----")
    log.info(body)


def main():
    logging.basicConfig(filename="/tmp/api.log", level=logging.INFO)
    log.info("==========START==========")   
    
    request = gateway.Request(os.environ)
    logRequest(method, uri, protocol, headers, body, env)

    response = io.StringIO()

    method = os.environ["REQUEST_METHOD"] 
    if method == "OPTIONS": 
        handleOptions(headers, body, response)
    elif method == "GET":
        handleGet(headers, body, response)
    elif method == "POST":
        handlePost(headers, body, response)

    content = response.getvalue()
    response.close()

    print(content)
    log.info(content)


if __name__ == '__main__':
    main()

