#!/usr/bin/env python3

import http
import json
import logging
import os
import sys

import gateway

log = logging.getLogger(__name__)


def handle_OPTIONS(request, response):
    log.info("handle_OPTIONS")
    
    ALLOWED_ORIGINS = "null"
    ALLOWED_HEADERS = "Content-Type"
    ALLOWED_METHODS = "OPTIONS, GET, POST"
    
    response.header("Access-Control-Allow-Origin", f"{ALLOWED_ORIGINS}")
    response.header("Access-Control-Allow-Headers", f"{ALLOWED_HEADERS}")
    response.header("Access-Control-Allow-Methods", f"{ALLOWED_METHODS}")

    response.set_status(http.HTTPStatus.NO_CONTENT)


def handle_POST(request, response):
    log.info(f"handle_POST: {request.body}")

    requestdata = json.loads(request.body)
    log.info(f"request data: {requestdata}")
    id = requestdata["id"]
    path = request.system["DOCUMENT_ROOT"] + "/../../data/" + id + ".metadata"

    # Start with empty metadata
    metadata = {}

    # Read in the metadata if we already have a file
    if os.path.exists(path):
        with open(path, "r") as file:
            try:
                metadata = json.load(file)
            except json.JSONDecodeError:
                log.info("could not parse metadata file")

    # Update the offer or answer metadata
    for key in requestdata.keys():
        metadata[key] = requestdata[key]

    # Open file for writing with truncation (using "a+" above does not allow overwriting)
    with open(path, "w") as file:
        # Format the dump to reduce deltas when diffing between versions
        json.dump(metadata, file, indent=2, sort_keys=True)
       
    response.set_status(http.HTTPStatus.OK)


def handle_GET(request, response):
    log.info("handle_GET")

    id = "abcd"
    path = request.system["DOCUMENT_ROOT"] + "/../../data/" + id + ".metadata"

    response.set_header("Access-Control-Allow-Origin", "null")
    response.set_header("Content-Type", "application/json")

    # Read in the metadata if we already have a file
    if os.path.exists(path):
        with open(path, "r") as file:
            try:
                metadata = json.load(file)
            except json.JSONDecodeError:
                log.info("could not parse metadata file")
        
        metadata["id"] = id
        formatted_metadata = json.dumps(metadata, indent=2, sort_keys=True)
        response.append_to_body(formatted_metadata)

    response.set_status(http.HTTPStatus.OK)


def main():
    logging.basicConfig(filename="/tmp/api.log", level=logging.INFO)
    log.info("==========NEW REQUEST==========")   
    
    request = gateway.ApacheRequest(os.environ, sys.stdin.read())
    log.info(request)

    response = gateway.ApacheResponse()
    
    match request.method:
        case http.HTTPMethod.OPTIONS: 
            handle_OPTIONS(request, response)
        case http.HTTPMethod.GET:
            handle_GET(request, response)
        case http.HTTPMethod.POST:
            handle_POST(request, response)
        case _:
            log.info(f"Method: {request.method} not found")

    raw_response = response.flush()
    log.info(raw_response)


if __name__ == '__main__':
    main()