#!/usr/bin/env python3
import os
import sys

log = open("api.log", "a")

print("Access-Control-Allow-Headers: Content-Type\n")
print("Access-Control-Allow-Methods: POST, GET, OPTIONS, DELETE\n")
print("Access-Control-Allow-Origin: *\n")
print("Content-Type: application/json\n")


{
  "hello": "world"
}


